---
version: 3.8.5
min_ruby_version: 2.4.0
name: WebUI Library
description: Front-end libraries developed by Titus
repository: https://github.com/TitusTech/webui-lib/wiki
# timezone: America/Los_Angeles
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: ""
  values:
    image: "/img/titus-logo.png"

# plugins:
# - jekyll-avatar
# - jekyll-feed
# - jekyll-mentions
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jemoji

feed:
  categories:
    - release

sass:
  style: compressed

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- icomoon-selection.json
- readme.md
